rm -rf brook
rm -rf hysteria
rm -rf naiveproxy
rm -rf pdnsd-alt
rm -rf shadowsocks-rust
rm -rf shadowsocksr-libev
rm -rf simple-obfs
rm -rf ssocks
rm -rf trojan-go
rm -rf trojan-plus
rm -rf trojan
rm -rf tuic-client
rm -rf v2ray-core
rm -rf v2ray-geodata
rm -rf v2ray-plugin
rm -rf xray-core
rm -rf xray-plugin
