name: Python CI

on:
  workflow_dispatch: 

env:
  PART1_SH: .github/part1.sh

jobs:
  clone_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: code
        run: |
          git clone --depth 1 -b main https://github.com/xiaorouji/openwrt-passwall-packages packages
          chmod +x $GITHUB_WORKSPACE/$PART1_SH
          cd packages
          $GITHUB_WORKSPACE/$PART1_SH
          cd ..
          cp -f .github/Makefile packages/sing-box

          
      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b pularv
          rm -rf .github
          rm -f README.md
          cp -r packages/* .
          cp -r packages/.github .
          rm -rf packages
          git add .
          git commit -m "commit"
          git push --force origin pularv
